defaults: &defaults
  docker:
    - image: circleci/openjdk:8-jdk
  working_directory: /home/circleci/project

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - java-dependencies-{{ checksum "./CitibikeApiProducer/build.gradle" }}
      - restore_cache:
          keys:
            - scala-dependencies-{{ checksum "./RawDataSaver/build.sbt" }}-{{ checksum "./StationConsumer/build.sbt"}}-{{ checksum "./StationTransformerNYC/build.sbt"}}
      - run:
          command: ./sbin/buildAll.sh
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - CitibikeApiProducer/build/
            - RawDataSaver/target/
            - StationConsumer/target/
            - StationTransformerNYC/target/
      - run:
          command: ls /home/circleci/project/
      - save_cache:
          key: scala-dependencies-{{ checksum "./RawDataSaver/build.sbt" }}-{{ checksum "./StationConsumer/build.sbt"}}-{{ checksum "./StationTransformerNYC/build.sbt"}}
          paths:
            - "~/.ivy2/cache"
      - save_cache:
          key: java-dependencies-{{ checksum "./CitibikeApiProducer/build.gradle" }}
          paths:
            - "~/.gradle"

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - add_ssh_keys:
          fingerprints:
            - "f0:79:be:b9:24:6d:88:1b:0a:d3:fb:b3:8f:55:9c:bb"
      - run:
          command: ./sbin/deploy.sh $BASTION_PUBLIC_IP $TRAINING_COHORT

  set-kafka-retention-period:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - add_ssh_keys:
          fingerprints:
            - "f0:79:be:b9:24:6d:88:1b:0a:d3:fb:b3:8f:55:9c:bb"
      - run:
          command: ./sbin/setKafkaRetentionPeriod.sh $BASTION_PUBLIC_IP $TRAINING_COHORT

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - start
      - approve-deploy:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - approve-deploy

      - approve-set-kafka-retention-period:
          type: approval
      - set-kafka-retention-period:
          requires:
            - approve-set-kafka-retention-period

